
#ifndef CUTTER_CONFIG_H
#define CUTTER_CONFIG_H

#define CUTTER_VERSION_MAJOR 1
#define CUTTER_VERSION_MINOR 10
#define CUTTER_VERSION_PATCH 2

#define CUTTER_VERSION_FULL "1.10.2"

#define CUTTER_EXTRA_PLUGIN_DIRS ""

#endif
